const Arr = [
    <img 
        className='card'
        src={require('../../icons&pics/Alexander-Arnold.png')}
        alt='github'>
    </img>,
    <img 
        className='card'
        src={require('../../icons&pics/Benzema.png')}
        alt='github'>
    </img>,
    <img 
        className='card'
        src={require('../../icons&pics/DeBruyne.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/DePaul.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Messi.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Son.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Ronaldo.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Lewandowski.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Neuer.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Kanté.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Kroos.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Pedri.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Neymar.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/SergioRamos.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Valverde.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Vinícius.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Foden.png')}
        alt='github'>
    </img>,
    <img
        className='card' 
        src={require('../../icons&pics/Haaland.png')}
        alt='github'>
    </img>,

   
]

export default Arr;